source 'https://rubygems.org'

gem 'rake'
gem 'thin'
gem 'sinatra'
gem 'sinatra-contrib'
gem 'sinatra-flash', :require => 'sinatra/flash'
gem 'pg'
gem 'data_mapper'
gem 'dm-sqlite-adapter'
gem 'dm-postgres-adapter'